### ISSUE TITLE
options nestingLevel not working correctly

### ISSUE THREAD

**Issue by Nurzzzone** [hesamurai/nested-sort#73]
If you set nestingLevel to 1 it works only for the 1 level elements not inner

![image](https://user-images.githubusercontent.com/73385787/171784513-cfbac945-8c1e-43e9-b35a-b47d0ffb9859.png)

**Comment by Askhanir** [comment]
Hello,
I noticed the same problem.
Has a solution been found?
Thanks for help.

**Comment by hesamurai** [comment]
Hello folks!

Sorry for the very late reply but I managed to patch the nesting levels behaviour today on:
https://github.com/hesamurai/nested-sort/pull/81

You can see the new behaviour here: https://www.hesamurai.com/nested-sort/latest

Please let me know if you meant something else.

**Comment by hesamurai** [comment]
I fixed another bug in this regard:
https://github.com/hesamurai/nested-sort/pull/91
